/**
 * Central registry for syllabus topics.
 * These are used as context for the Gemini model to categorize past paper pages.
 */

module.exports = {
  // Mathematics
  "9709": [
    "Quadratics",
    "Functions",
    "Coordinate Geometry",
    "Circular Measure",
    "Trigonometry",
    "Series",
    "Differentiation",
    "Integration",
    "Vectors",
    "Differential Equations",
    "Complex Numbers",
    "Forces and Equilibrium",
    "Kinematics of Motion",
    "Newton’s Laws of Motion",
    "Momentum",
    "Energy, Work, and Power",
    "Representation of Data",
    "Permutations and Combinations",
    "Probability",
    "Discrete Random Variables",
    "The Normal Distribution",
    "The Poisson Distribution",
    "Sampling and Estimation",
    "Hypothesis Tests"
  ],
  // Physics
  "9702": [
    "Physical Quantities and Units",
    "Measurement Techniques",
    "Kinematics",
    "Dynamics",
    "Forces, Density and Pressure",
    "Work, Energy and Power",
    "Deformation of Solids",
    "Waves",
    "Superposition",
    "Electric Fields",
    "Current of Electricity",
    "D.C. Circuits",
    "Particle Physics",
    "Motion in a Circle",
    "Gravitational Fields",
    "Temperature",
    "Ideal Gases",
    "Thermodynamics",
    "Oscillations",
    "Communication",
    "Capacitance",
    "Electronics",
    "Magnetic Fields",
    "Electromagnetic Induction",
    "Alternating Currents",
    "Quantum Physics"
  ],
  // Chemistry
  "9701": [
    "Atoms, Molecules and Stoichiometry",
    "Atomic Structure",
    "Chemical Bonding",
    "States of Matter",
    "Chemical Energetics",
    "Electrochemistry",
    "Equilibria",
    "Reaction Kinetics",
    "The Periodic Table",
    "Nitrogen and Sulfur",
    "An Introduction to Organic Chemistry",
    "Hydrocarbons",
    "Halogen Derivatives",
    "Hydroxy Compounds",
    "Carbonyl Compounds",
    "Carboxylic Acids and Derivatives",
    "Nitrogen Compounds",
    "Polymerisation",
    "Analytical Techniques",
    "Organic Synthesis"
  ],
  // Biology
  "9700": [
    "Cell Structure",
    "Biological Molecules",
    "Enzymes",
    "Cell Membranes and Transport",
    "The Mitotic Cell Cycle",
    "Nucleic Acids and Protein Synthesis",
    "Transport in Plants",
    "Transport in Mammals",
    "Gas Exchange and Smoking",
    "Infectious Disease",
    "Immunity",
    "Energy and Respiration",
    "Photosynthesis",
    "Homeostasis",
    "Control and Co-ordination",
    "Inherited Change",
    "Selection and Evolution",
    "Biodiversity, Classification and Conservation",
    "Genetic Technology"
  ]
}
